Imported Upstream version 1.1.99.7

diff --git a/src/synthesis/configure b/src/synthesis/configure
--- a/src/synthesis/configure
+++ b/src/synthesis/configure
@@ -764,6 +764,7 @@ PKG_CONFIG
 COND_DOXYGEN_FALSE
 COND_DOXYGEN_TRUE
 PIC_CXXFLAGS
+SYNTHESIS_WFLAGS
 CXXCPP
 CPP
 OTOOL64
@@ -886,6 +887,7 @@ with_pic
 enable_fast_install
 with_gnu_ld
 enable_libtool_lock
+enable_warnings
 enable_debug_logs
 enable_sqlite
 enable_regex
@@ -1542,6 +1544,8 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-warnings=[min|max|fatal|no]
+                          control compiler pickyness [min]
   --debug-logs            For developers: add links to call location to HTML
                           log files. Depends on Doxygen (for HTML version of
                           source) and g++ (for __PRETTY_FUNCTION__).
@@ -2972,7 +2976,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=synthesis
- VERSION=3.4.0.16.1
+ VERSION=3.4.0.16.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -5063,13 +5067,13 @@ if test "${lt_cv_nm_interface+set}" = set; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5066: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5070: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5069: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5073: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5072: output\"" >&5)
+  (eval echo "\"\$as_me:5076: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6275,7 +6279,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6278 "configure"' > conftest.$ac_ext
+  echo '#line 6282 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8301,6 +8305,10 @@ _lt_linker_boilerplate=`cat conftest.err`
 $RM -r conftest*
 
 
+## CAVEAT EMPTOR:
+## There is no encapsulation within the following macros, do not change
+## the running order or otherwise move them around unless you know exactly
+## what you are doing...
 if test -n "$compiler"; then
 
 lt_prog_compiler_no_builtin_flag=
@@ -8326,11 +8334,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8329: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8337: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8333: \$? = $ac_status" >&5
+   echo "$as_me:8341: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8665,11 +8673,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8668: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8676: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8672: \$? = $ac_status" >&5
+   echo "$as_me:8680: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8770,11 +8778,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8773: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8781: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8777: \$? = $ac_status" >&5
+   echo "$as_me:8785: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8825,11 +8833,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8828: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8836: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8832: \$? = $ac_status" >&5
+   echo "$as_me:8840: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11209,7 +11217,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11212 "configure"
+#line 11220 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11305,7 +11313,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11308 "configure"
+#line 11316 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13261,11 +13269,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13264: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13272: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13268: \$? = $ac_status" >&5
+   echo "$as_me:13276: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13360,11 +13368,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13363: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13371: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13367: \$? = $ac_status" >&5
+   echo "$as_me:13375: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13412,11 +13420,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13415: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13423: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13419: \$? = $ac_status" >&5
+   echo "$as_me:13427: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14535,6 +14543,89 @@ if test "$am_t" != yes; then
    CC="$am_aux_dir/compile $CC"
 fi
 
+
+
+# --enable-warning=min/max/fatal/none
+# Check whether --enable-warnings was given.
+if test "${enable_warnings+set}" = set; then :
+  enableval=$enable_warnings; dk_enable_warnings=$enableval
+else
+  dk_enable_warnings=min
+fi
+
+dk_lang=
+case $ac_compile in
+  *'$CXXFLAGS '*)
+    dk_lang='C++'
+    dk_cc=$CXX
+    dk_conftest=conftest.${ac_ext-cc}
+    ;;
+  *'$CFLAGS '*)
+    dk_lang=C
+    dk_cc=$CC
+    dk_conftest=conftest.${ac_ext-c}
+    ;;
+esac
+
+if test "x$dk_lang" != x; then :
+
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking which $dk_lang compiler warning flags to use" >&5
+$as_echo_n "checking which $dk_lang compiler warning flags to use... " >&6; }
+
+  case $dk_enable_warnings in
+    no) dk_warning_flags=;;
+    max) dk_warning_flags="-Wall -Wno-unknown-pragmas";;
+    fatal) dk_warning_flags="-Wall -Wno-unknown-pragmas -Werror";;
+    *) dk_warning_flags="-Wall";;
+  esac
+
+  dk_deprecation_flags=
+  dk_tested_flags=
+
+  if test "x$dk_warning_flags" != x; then :
+
+    # Keep in mind that the dummy source must be devoid of any
+    # problems that might cause diagnostics.
+    cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+int main(int argc, char** argv) { return (argv != 0) ? argc : 0; }
+_ACEOF
+
+    for dk_flag in $dk_warning_flags
+    do
+      # Test whether the compiler accepts the flag. GCC doesn't bail
+      # out when given an unsupported flag but prints a warning, so
+      # check the compiler output instead.
+      dk_cc_out=`$dk_cc $dk_tested_flags $dk_flag -c "$dk_conftest" 2>&1 || echo failed`
+      rm -f "conftest.${OBJEXT-o}"
+
+      if test "x$dk_cc_out" = x; then :
+
+        if test "x$dk_tested_flags" = x; then :
+  dk_tested_flags=$dk_flag
+else
+  dk_tested_flags="$dk_tested_flags $dk_flag"
+fi
+
+else
+
+        echo "$dk_cc_out" >&5
+
+fi
+    done
+
+    rm -f "$dk_conftest"
+
+fi
+  dk_all_flags=$dk_deprecation_flags$dk_tested_flags
+  SYNTHESIS_WFLAGS=$dk_all_flags
+
+
+  test "x$dk_all_flags" != x || dk_all_flags=none
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $dk_all_flags" >&5
+$as_echo "$dk_all_flags" >&6; }
+
+fi
 
 
 PIC_CXXFLAGS="$lt_prog_compiler_pic_CXX"
