Imported Upstream version 1.1.99.5a

diff --git a/configure-pre.in b/configure-pre.in
--- a/configure-pre.in
+++ b/configure-pre.in
@@ -8,11 +8,37 @@ dnl Invoke autogen.sh to produce a configure script.
 #
 # Starting with the 1.1 release cycle, the rpm-style
 # .99 pseudo-version number is used to mark a pre-release.
-AC_INIT([syncevolution], [1.1.1])
+AC_INIT([syncevolution], [1.1.99.5a])
 # STABLE_VERSION=1.0.1+
 AC_SUBST(STABLE_VERSION)
 
+# Default value for --enable/disable-release-mode.
+# Determined by gen-autotools.sh based on versioning.
+# Official, stable releases enable it, pre-releases
+# disable it.
+#
+# SyncEvolution >= 1.1.99.5: release mode by default
+define([STABLE_RELEASE], [yes])
+
+# Line above is patched by gen-autotools.sh. Handle
+# both "yes" and "no".
+define([STABLE_RELEASE_HELP], ifelse(STABLE_RELEASE,yes,--disable-release-mode,--enable-release-mode))
+
+AC_ARG_ENABLE(release-mode,
+              AS_HELP_STRING([STABLE_RELEASE_HELP],
+                             [Controls whether resulting binary is for end-users or
+                              testers/developers. For example, stable releases automatically
+                              migrate on-disk files without asking, whereas other releases
+                              ask before making downgrades impossible (or difficult).
+                              Default in this source code is
+                              "stable release: STABLE_RELEASE"]),
+              enable_release_mode="$enableval", enable_release_mode="STABLE_RELEASE")
+if test "$enable_release_mode" = "yes"; then
+   AC_DEFINE(SYNCEVOLUTION_STABLE_RELEASE, 1, [binary is meant for end-users])
+fi
+
 AM_INIT_AUTOMAKE([tar-ustar])
+AM_MAINTAINER_MODE([enable]) # needed for nightly builds where reconfiguration fails under certain chroots
 AC_CONFIG_MACRO_DIR([m4])
 define([SYNTHESISSRC_REPO], [])
 dnl Specify git revisions/branches without prefix, i.e., without 'origin'.
@@ -20,6 +46,11 @@ dnl We'll sort that out below.
 define([SYNTHESISSRC_REVISION], [syncevolution-0.9])
 AM_CONFIG_HEADER(config.h)
 AC_LIBTOOL_DLOPEN
+
+dnl check for programs.
+AC_PROG_CXX
+AC_PROG_LIBTOOL
+AC_PROG_MAKE_SET
 
 dnl default device type (see AC_DEFINE below)
 DEVICE_TYPE=workstation
@@ -80,6 +111,17 @@ AC_ARG_ENABLE(integration-tests,
                              [enables tests outside of the library (can be used together with normal builds of the library)]),
               enable_integration_tests="$enableval", enable_integration_tests="no")
 
+AC_ARG_ENABLE(buteo-tests,
+              AS_HELP_STRING([--enable-buteo-tests],
+                             [enables tests for Buteo sync framework. Not enabled when neither '--enable-unit-tests' nor '--enable-integration-tests' is specified]),
+              [ if test "$enable_unit_tests" = "yes" || test "$enable_integration_tests" = "yes" ; then
+                    enable_buteo_tests="$enableval"
+                else
+                    enable_buteo_tests="no"
+                fi], enable_buteo_tests="no")
+PKG_CHECK_MODULES(BUTEOSYNCPROFILE, [syncprofile], HAVE_SYNCPROFILE=yes, HAVE_SYNCPROFILE=no)
+PKG_CHECK_MODULES(BUTEOSYNCCOMMON, [synccommon], HAVE_SYNCCOMMON=yes, HAVE_SYNCCOMMON=no)
+
 AC_ARG_ENABLE(static-cxx,
               AS_HELP_STRING([--enable-static-cxx],
                              [build executables which contain libstdc++ instead of requiring suitable libstdc++.so to run]),
@@ -109,7 +151,7 @@ AC_SUBST(MODIFY_SYNCCOMPARE)
 AC_CHECK_HEADERS(signal.h dlfcn.h)
 
 # cppunit needed?
-if test $enable_unit_tests == "yes" || test $enable_integration_tests == yes; then
+if test $enable_unit_tests = "yes" || test $enable_integration_tests = yes; then
         CPPUNIT_CXXFLAGS=`cppunit-config --cflags` || AC_MSG_ERROR("cppunit-config --cflags failed - is it installed?")
         CPPUNIT_LDFLAGS=`cppunit-config --libs` || AC_MSG_ERROR("cppunit-config --libs failed - is it installed?")
 fi
@@ -122,10 +164,19 @@ fi
 if test "$enable_integration_tests" = "yes"; then
         AC_DEFINE(ENABLE_INTEGRATION_TESTS, 1, [enable integration tests inside the final library])
 fi
+if test "$enable_buteo_tests" = "yes"; then
+        AC_DEFINE(ENABLE_BUTEO_TESTS, 1, [enable buteo tests])
+        need_qt_modules="$need_qt_modules dbus xml"
+        AC_PATH_PROG(SQLITE3, sqlite3)
+        if test -z "$SQLITE3"; then
+            AC_ERROR([sqlite3 not found, is required for buteo testing])
+        fi
+fi
 AM_CONDITIONAL([ENABLE_UNIT_TESTS], [test "$enable_unit_tests" = "yes"])
 AM_CONDITIONAL([ENABLE_TESTING], [test "$enable_unit_tests" = "yes" || test "$enable_integration_tests" = "yes" ])
+AM_CONDITIONAL([ENABLE_BUTEO_TESTS], [test "$enable_buteo_tests" = "yes"])
 
-if test $enable_static_cxx == "yes"; then
+if test $enable_static_cxx = "yes"; then
         LIBS="$LIBS -L."
         CORE_LDADD_DEP=libstdc++.a
 fi
@@ -251,7 +302,8 @@ if test "$enable_bluetooth" = "yes"; then
    #
    # The source code checks the signature both by via pointer assignment and calling
    # it (better safe than sorry). One these should fail if the signature is not right.
-   AC_COMPILE_IFELSE([#include <bluetooth/sdp.h>
+   AC_COMPILE_IFELSE([AC_LANG_SOURCE([
+                      #include <bluetooth/sdp.h>
                       #include <bluetooth/sdp_lib.h>
                       sdp_record_t *(*extract_pdu)(const uint8_t *pdata, int bufsize, int *scanned) =
                            sdp_extract_pdu;
@@ -260,9 +312,10 @@ if test "$enable_bluetooth" = "yes"; then
                           int scanned;
                           sdp_extract_pdu(pdata, 100, &scanned);
                       }
-                     ],
+                     ])],
                      AC_DEFINE(HAVE_BLUEZ_BUFSIZE, 1, [base libbluetooth functions accept bufsize parameter]),
-                     AC_COMPILE_IFELSE([#include <bluetooth/sdp.h>
+                     AC_COMPILE_IFELSE([AC_LANG_SOURCE([
+                                        #include <bluetooth/sdp.h>
                                         #include <bluetooth/sdp_lib.h>
                                         sdp_record_t *(*extract_pdu)(const uint8_t *pdata, int bufsize, int *scanned) =
                                                sdp_extract_pdu_safe;
@@ -271,7 +324,7 @@ if test "$enable_bluetooth" = "yes"; then
                                             int scanned;        
                                             sdp_extract_pdu_safe(pdata, 100, &scanned);
                                         }
-                                       ],
+                                       ])],
                                        AC_DEFINE(HAVE_BLUEZ_SAFE, 1, [libbluetooth has _safe variants])))
    CFLAGS="$CFLAGS_old"
 
@@ -356,7 +409,7 @@ AC_ARG_ENABLE(dbus-service,
                              [enables building the dbus service executable and all related features
                              (the DBus wrapper library, command line usage of server, etc).]),
               enable_dbus_service="$enableval",
-              [if test $enable_gui == "no"; then
+              [if test $enable_gui = "no"; then
                   enable_dbus_service="no"
                else
                   enable_dbus_service="yes"
@@ -371,15 +424,68 @@ AC_ARG_ENABLE(gnome-keyring,
                test "$enable_gnome_keyring" = "yes" || test "$enable_gnome_keyring" = "no" || AC_ERROR([invalid value for --enable-gnome-keyring: $enable_gnome_keyring])
                test "$enable_gnome_keyring" = "no" || test "$HAVE_KEYRING" = "yes" || AC_ERROR([gnome-keyring-1 pkg not found, needed for --enable-gnome-keyring])],
               enable_gnome_keyring="$HAVE_KEYRING")
-if test $enable_gnome_keyring == "yes"; then
+if test $enable_gnome_keyring = "yes"; then
     AC_DEFINE(USE_GNOME_KEYRING, 1, [define if gnome keyring should be used in dbus service])
     PKG_CHECK_MODULES([KEYRING_2_20], [gnome-keyring-1 >= 2.20 ], KEYRING220=yes, KEYRING220=no)
-    if test $KEYRING220 == "yes"; then
+    if test $KEYRING220 = "yes"; then
         AC_DEFINE(GNOME_KEYRING_220, 1, [define if gnome keyring version is above 2.20])
     fi
 fi
 
-if test $enable_dbus_service == "yes"; then
+
+## Begin KWallet ##############################
+
+AC_CHECK_PROGS([QMAKE], [qmake qmake-qt4])
+
+if test "$QMAKE"; then
+   KDEKWALLETFOUND=yes
+   if ! test "$KDE_KWALLET_CFLAGS"; then
+      KDE_KWALLET_CFLAGS="-I`kde4-config --path include` -I`kde4-config --path include`/KDE -I`$QMAKE -query QT_INSTALL_HEADERS`"
+   fi
+   if ! test "$KDE_KWALLET_LIBS"; then
+      KDE_KWALLET_LIBS="-lkdeui -lkdecore `pkg-config --libs QtDBus`"
+   fi
+   AC_LANG_PUSH(C++)
+   old_CPPFLAGS="$CPPFLAGS"
+   CPPFLAGS="$CPPFLAGS $KDE_KWALLET_CFLAGS"
+   AC_CHECK_HEADERS(kwallet.h, [], [KDEKWALLETFOUND=no])
+   CPPFLAGS="$old_CPPFLAGS"
+   AC_LANG_POP(C++)
+else
+   KDEKWALLETFOUND=no
+fi
+
+# In contrast to the GNOME KEYRING, the KWallet is
+# currently considered optional. "configure" will never enable
+# by default, because that is a change that might not be
+# expected by traditional users.
+AC_ARG_ENABLE(kwallet,
+              AS_HELP_STRING([--enable-kwallet], [enable access to KWallet]),
+              [use_kde_kwallet="$enableval"
+              test $KDEKWALLETFOUND = "yes" || test "$use_kde_kwallet" = "no" || AC_MSG_ERROR([kwallet.pc not found. Install it to compile with the KWallet enabled.])],
+              [use_kde_kwallet="no"])
+
+if test "$use_kde_kwallet" = "yes"; then
+    # conditional compilation in preprocessor
+    AC_DEFINE(USE_KDE_KWALLET, 1, [KWallet available])
+    # TODO: KWallet needs Qt. Enable the Qt check in
+    # configure-post.in, otherwise it fails to compiler
+    # when none of the backends ask for Qt.
+else
+    # avoid unneeded dependencies on KWallet
+    KDE_KWALLET_CFLAGS=
+    KDE_KWALLET_LIBS=
+fi
+AC_SUBST(KDE_KWALLET_LIBS)
+AC_SUBST(KDE_KWALLET_CFLAGS)
+
+# conditional compilation in make
+AM_CONDITIONAL([USE_KDE_KWALLET], [test "$use_kde_kwallet" = "yes"])
+
+## End KWallet ################################
+
+
+if test $enable_dbus_service = "yes"; then
     if test -z "$XSLT"; then
        AC_ERROR([xsltproc not found, is required for D-Bus service])
     fi
@@ -396,11 +502,28 @@ if test $enable_dbus_service == "yes"; then
     PKG_CHECK_MODULES(LIBNOTIFY, [libnotify gtk+-2.0], HAVE_LIBNOTIFY=yes, HAVE_LIBNOTIFY=no)
     AC_ARG_ENABLE(notify,
                   AS_HELP_STRING([--enable-notify],
-                                 [send notifications for automatic sync events]),
+                                 [send notifications for automatic sync events, using libnotify]),
                   [ test "$enableval" = "no" || test $HAVE_LIBNOTIFY = "yes" || AC_ERROR([required libnotify package not found]) ],
-                  [ test $HAVE_LIBNOTIFY = "yes" || AC_ERROR([required libnotify package not found, use --disable-notify to compile without notifications]) ])
-    if test $HAVE_LIBNOTIFY == "yes"; then
+                  [ test $HAVE_LIBNOTIFY = "yes" || AC_ERROR([required libnotify package not found, use --disable-notify to compile without libnotify based notifications]) ])
+    if test $HAVE_LIBNOTIFY = "yes"; then
         AC_DEFINE(HAS_NOTIFY, 1, [define if libnotify could be used in dbus service])
+    fi
+
+    # Here we're using QtGui too because mlite fails to depend on it,
+    # despite using QAction.
+    PKG_CHECK_MODULES(MLITE, [mlite QtGui], HAVE_MLITE=yes, HAVE_MLITE=no)
+    AC_ARG_ENABLE(mlite,
+                  AS_HELP_STRING([--enable-mlite],
+                                 [send notifications for automatic sync events, using mlite (off by default)]),
+                  [ enable_mlite="$enableval"
+                    test "$enableval" = "no" || test $HAVE_MLITE = "yes" || AC_ERROR([required mlite package not found]) ],
+                  [ enable_mlite="no" ])
+    if test $enable_mlite = "yes"; then
+        AC_DEFINE(HAS_MLITE, 1, [define if mlite could be used in dbus service])
+    else
+        # don't use mlite, even if found
+        MLITE_CFLAGS=
+        MLITE_LIBS=
     fi
     AC_DEFINE(DBUS_SERVICE, 1, [define if dbus service is enabled])
 fi
@@ -413,12 +536,16 @@ AC_SUBST(KEYRING_LIBS)
 AC_SUBST(LIBNOTIFY_CFLAGS)
 AC_SUBST(LIBNOTIFY_LIBS)
 AC_SUBST(LIBEXECDIR)
+AC_SUBST(BUTEOSYNCPROFILE_LIBS)
+AC_SUBST(BUTEOSYNCPROFILE_CFLAGS)
+AC_SUBST(BUTEOSYNCCOMMON_LIBS)
+AC_SUBST(BUTEOSYNCCOMMON_CFLAGS)
 
 DBUS_SERVICES_DIR="${datadir}/dbus-1/services"
 AC_SUBST(DBUS_SERVICES_DIR)
 AC_DEFINE_UNQUOTED(DBUS_SERVICES_DIR, "$DBUS_SERVICES_DIR", [Location of D-Bus services directory])
 
-if test $enable_gui != "no" || test $enable_dbus_service == "yes"; then
+if test $enable_gui != "no" || test $enable_dbus_service = "yes"; then
     IT_PROG_INTLTOOL([0.37.1])
     GETTEXT_PACKAGE=syncevolution
     AC_DEFINE_UNQUOTED(GETTEXT_PACKAGE, "$GETTEXT_PACKAGE", [The gettext package name])
@@ -441,16 +568,16 @@ if test $enable_gui != "no"; then
     AC_PATH_PROG(GLIB_GENMARSHAL, glib-genmarshal)
 
     gui_modules="glib-2.0 dbus-glib-1 >= 0.60 gtk+-2.0 libglade-2.0 gio-2.0"
-    if test $enable_gui == "moblin"; then
+    if test $enable_gui = "moblin"; then
         AC_DEFINE(USE_MOBLIN_UX, 1, [Use Moblin UI widgets])
     fi
-    if test $enable_gui == "moblin" -o $enable_gui == "all"; then
+    if test $enable_gui = "moblin" -o $enable_gui = "all"; then
         gui_modules="$guimodules mx-gtk-1.0"
 
         PKG_CHECK_MODULES(MX_GTK_0_99_1, mx-gtk-1.0 >= 0.99.1,
                           have_mx_gtk_0_99_1="yes",
                           have_mx_gtk_0_99_1="no")
-        if test $have_mx_gtk_0_99_1 == "yes"; then
+        if test $have_mx_gtk_0_99_1 = "yes"; then
             AC_DEFINE(MX_GTK_0_99_1, 1, [we have Mx-Gtk 0.99.1 or better])
         fi
     fi
@@ -458,7 +585,7 @@ if test $enable_gui != "no"; then
     PKG_CHECK_MODULES(UNIQUE, unique-1.0,
                       have_unique="yes",
                       have_unique="no")
-    if test $have_unique == "yes"; then
+    if test $have_unique = "yes"; then
         gui_modules="$gui_modules unique-1.0" 
         AC_DEFINE(ENABLE_UNIQUE, 1, [enable single-app-instance functionality])
     fi
@@ -466,7 +593,7 @@ if test $enable_gui != "no"; then
     PKG_CHECK_MODULES(GTK_2_18, gtk+-2.0 >= 2.18,
                       have_gtk_2_18="yes",
                       have_gtk_2_18="no")
-    if test $have_gtk_2_18 == "yes"; then
+    if test $have_gtk_2_18 = "yes"; then
         AC_DEFINE(GTK_2_18, 1, [we have GTK+ 2.18 or better])
     fi
 
@@ -500,10 +627,10 @@ AC_ARG_WITH(rst2man,
                             An explicit --without-rst2man or not having it installed turn off
                             building of man pages.]),
             [RST2MAN=$withval
-             if test "$RST2MAN" == "yes"; then
+             if test "$RST2MAN" = "yes"; then
                  AC_PATH_PROG(RST2MAN, rst2man, "no")
              fi
-             test "$RST2MAN" == "no" || test -x "$RST2MAN" || AC_ERROR([--with-rst2man=$RST2MAN: tool not found])],
+             test "$RST2MAN" = "no" || test -x "$RST2MAN" || AC_ERROR([--with-rst2man=$RST2MAN: tool not found])],
             [AC_PATH_PROG(RST2MAN, rst2man, "no")])
 AM_CONDITIONAL([COND_MAN_PAGES], [test "$RST2MAN" != "no"])
 
@@ -514,10 +641,10 @@ AC_ARG_WITH(rst2html,
                             An explicit --without-rst2html or not having it installed turn off
                             building of README in HTML format.]),
             [RST2HTML=$withval
-             if test "$RST2HTML" == "yes"; then
+             if test "$RST2HTML" = "yes"; then
                  AC_PATH_PROG(RST2HTML, rst2html, "no")
              fi
-             test "$RST2HTML" == "no" || test -x "$RST2HTML" || AC_ERROR([--with-rst2html=$RST2HTML: tool not found])],
+             test "$RST2HTML" = "no" || test -x "$RST2HTML" || AC_ERROR([--with-rst2html=$RST2HTML: tool not found])],
             [AC_PATH_PROG(RST2HTML, rst2html, "no")])
 AM_CONDITIONAL([COND_HTML_README], [test "$RST2HTML" != "no"])
 
@@ -586,7 +713,7 @@ elif test "$SYNTHESISSRC" != "none" && test -d $srcdir/src/synthesis; then
     esac
 elif test "$enable_shared" = "no"; then
     # link against engine
-    PKG_CHECK_MODULES(SYNTHESIS, "synthesis")
+    PKG_CHECK_MODULES([SYNTHESIS], [synthesis >= 3.4])
     SYNTHESIS_ENGINE="$SYNTHESIS_LIBS -lsynthesis"
 else
     # link against SDK alone, except in client-test
@@ -594,7 +721,7 @@ else
     #SYNTHESIS_ENGINE="`echo $SYNTHESIS_LIBS | sed -e 's/-lsynthesisstubs/-lsynthesis/'`"
 
     # can't use the SDK alone because of sysync::SySyncDebugPuts()
-    PKG_CHECK_MODULES(SYNTHESIS, "synthesis")
+    PKG_CHECK_MODULES([SYNTHESIS], [synthesis >= 3.4])
     SYNTHESIS_ENGINE="$SYNTHESIS_LIBS"
 fi
 
